gios:
  topology:
    retention-period:
      amount: 72
      time-unit: HOURS
    window-size:
      amount: 72
      time-unit: HOURS
  installation-topic: gios.installation
  measurement-topic: gios.measurement
  measurement-store: gios-measurement-store

quarkus:
  application:
    name: gios-aggregator
  kafka-streams:
    bootstrap-servers: 10.1.1.51:9092
    topics:
      - gios.installation
      - gios.measurement

kafka-streams:
  cache:
    max:
      bytes:
        byfferring: 10240
  commit:
    interval:
      ms: 1000
  metadata:
    max:
      age:
        ms: 500
  auto:
    offset:
      reset:
        earliest
  metrics:
    recording:
      level: INFO
  heartbeat:
    interval:
      ms: 200
  default:
    production:
      exception:
        handler: pl.airq.aggregator.serde.ProductionErrorHandler
    deserialization:
      exception:
        handler: pl.airq.aggregator.serde.DeserializationErrorHandler

"%dev":
  quarkus:
    kafka-streams:
      bootstrap-servers: localhost:9092

"%test":
  gios:
    topology:
      retention-period:
        amount: 10
        time-unit: SECONDS
      window-size:
        amount: 10
        time-unit: SECONDS
